import { FormEvent, ReactNode, useEffect, useState } from "react";
import { Navigate, NavLink, Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";
import {
  Activity, ArrowLeft, BarChart3, Bell, BriefcaseBusiness, Building2, CalendarDays, CheckCircle2,
  ChevronDown, ChevronUp, Clock3, Edit3, Eye, EyeOff, FileText, HardHat, LayoutDashboard, LogOut, Menu, MoreHorizontal,
  Moon, Plus, Search, Settings, ShieldCheck, Sun, Trash2, UserCheck, Users, X, XCircle,
} from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api } from "./api";
import { Employee, employees as fallbackEmployees, roles as fallbackRoles, sites as fallbackSites } from "./data";

type ApiEmployee = { id:number; id_api?:string; nome:string; cpf:string; matricula:string; telefone:string|null; email:string|null; cargo_id?:number|null; cargo_nome:string|null; obras:string|null; ativo:number };
type ApiSite = { id:number; nome:string; codigo:string; endereco:string|null; cidade:string|null; responsavel:string|null; data_inicio:string|null; data_fim:string|null; ativa:number };
type ApiRole = { id:number; nome:string; descricao:string|null; ativo:number };
type ApiJourney = { id:number; obra_id:number; obra_nome:string; obra_codigo:string; data:string; hora_inicio_prevista:string; hora_fim_prevista:string; status:string; total_funcionarios:number; presentes:number };
type ApiJourneyDetail = ApiJourney & { funcionarios:Array<{jornada_funcionario_id:number; funcionario_id:number; nome:string; matricula:string; cargo_nome:string|null; status:string; primeira_batida:string|null; ultima_batida:string|null; total_batidas:number}> };
type ApiPunch = { id:number; tipo:"ENTRADA"|"SAIDA"; data_hora:string; observacao:string|null };
type DashboardData = { data:string; resumo:{funcionariosAtivos:number; obrasAtivas:number; jornadasHoje:number; presentes:number; pendentes:number; batidas:number}; porObra:Array<{id:number; nome:string; codigo:string; jornada_id:number; status:string; total_funcionarios:number; presentes:number; pendentes:number}>; presencaDiaria:Array<{data:string;presentes:number}> };
type LoginResponse = { token:string; gestor:{id:number; nome:string; cpf:string; email:string} };
type ApiAttendance = { id:string; date:string; employeeId:string; employeeName:string; roleName:string; worksiteName:string; timeEntryCount:number; firstTime:string|null; lastTime:string|null; timeStatus:"sem_ponto"|"incompleto"|"completo"; pointPresence:boolean; foremanStatus:"nao_marcado"|"presente"|"ausente"; foremanObservation:string };

const pageTitles:Record<string,string> = {"/dashboard":"Visão geral","/funcionarios":"Funcionários","/jornadas":"Lista de presença","/conferencia":"Conferência","/obras":"Obras","/cargos":"Cargos"};
const demoDashboard:DashboardData = {data:new Date().toISOString().slice(0,10),resumo:{funcionariosAtivos:0,obrasAtivas:0,jornadasHoje:0,presentes:0,pendentes:0,batidas:0},porObra:[],presencaDiaria:[]};
const fallbackApiSites:ApiSite[] = [];
const fallbackApiRoles:ApiRole[] = [];
const fallbackApiEmployees:ApiEmployee[] = [];
const formatDate=(v:string)=>v.split("-").reverse().join("/")||"--";
const formatTime=(v:string|null)=>v?v.slice(11,16):"--:--";
const normalizeText=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const matchesSearch=(text:string,search:string)=>normalizeText(text).includes(normalizeText(search));
const employeeFromApi=(x:ApiEmployee):Employee=>({id:x.id,name:x.nome,cpf:x.cpf,role:x.cargo_nome||"Sem cargo",site:x.obras||"Sem obra",phone:x.telefone||"-",status:x.ativo?"Ativo":"Inativo",matricula:x.matricula,email:x.email||"",cargoId:x.cargo_id ?? undefined});
const activeWorksiteId=()=>localStorage.getItem("toth-obra")||"";
function useActiveWorksite(){const [id,setId]=useState(activeWorksiteId());useEffect(()=>{const update=()=>setId(activeWorksiteId());window.addEventListener("toth-worksite-change",update);return()=>window.removeEventListener("toth-worksite-change",update)},[]);return id}

function Status({value}:{value:string}){const display=value==="ENCERRADA"?"FINALIZADO":value==="ABERTA"?"ABERTO":value;const green=["Regular","REGULAR","ABONADO","Ativo","Em andamento","ENCERRADA","FINALIZADO","Presente","PRESENTE"].includes(value)||display==="FINALIZADO";const yellow=["Atenção","Pendente","PENDENTE","INCONSISTENTE","ABERTA"].includes(value);return <span className={`status ${green?"green":yellow?"yellow":"red"}`}><i/>{display}</span>}
function Button({children,variant="primary",onClick,type="button"}:{children:ReactNode;variant?:string;onClick?:()=>void|Promise<void>;type?:"button"|"submit"}){return <button className={`button ${variant}`} onClick={onClick} type={type}>{children}</button>}
function PageIntro({title,text,action}:{title:ReactNode;text:string;action?:ReactNode}){return <div className="page-intro"><div><h2>{title}</h2><p>{text}</p></div>{action}</div>}
function Toolbar({search,setSearch,onFilter,active}:{search:string;setSearch:(v:string)=>void;onFilter:()=>void;active:boolean}){return <div className="toolbar"><label><Search/><input placeholder="Buscar..." value={search} onChange={e=>setSearch(e.target.value)}/></label><button className={`filter ${active?"active":""}`} onClick={onFilter}><FileText/>Filtros</button></div>}

function Landing({onLogin}:{onLogin:()=>void}){
  const [open,setOpen]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[showPassword,setShowPassword]=useState(false);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setLoading(true);setError("");const f=new FormData(e.currentTarget);const result=await api<LoginResponse>("/login",{method:"POST",body:JSON.stringify({cpf:f.get("cpf"),senha:f.get("senha")})});setLoading(false);if(!result){setError("CPF ou senha inválidos.");return}localStorage.setItem("toth-token",result.token);localStorage.setItem("toth-gestor",JSON.stringify(result.gestor));onLogin()};
  return <main className="landing"><nav className="landing-nav"><img src="/assets/logo-nome.png"/><button onClick={()=>setOpen(true)}>Entrar</button></nav><section className="hero"><div className="hero-copy"><span className="eyebrow">GESTÃO DE PONTO INTELIGENTE</span><h1>Tempo sob controle.<br/><strong>Obras no ritmo.</strong></h1><p>Transforme a gestão das suas equipes com registros confiáveis, acompanhamento em tempo real e decisões mais rápidas.</p><div className="hero-actions"><Button onClick={()=>setOpen(true)}>Começar agora</Button><span><ShieldCheck/>Dados seguros e confiáveis</span></div></div><div className="hero-art"><div className="glow"/><img src="/assets/toth-bird.png"/><div className="float-card fc-one"><CheckCircle2/><b>Equipe presente</b><span>Dados em tempo real</span></div><div className="float-card fc-two"><Clock3/><b>Ponto registrado</b><span>Sincronizado com a API</span></div></div></section><section className="features">{[{i:<Activity/>,t:"Tempo real",d:"Acompanhe sua equipe de onde estiver."},{i:<BarChart3/>,t:"Decisões claras",d:"Indicadores que fazem sentido para sua obra."},{i:<ShieldCheck/>,t:"Confiável",d:"Registros organizados e sempre acessíveis."}].map(x=><article key={x.t}>{x.i}<div><b>{x.t}</b><p>{x.d}</p></div></article>)}</section>{open&&<div className="modal-backdrop"><div className="login-card"><button className="close" onClick={()=>setOpen(false)}><X/></button><img src="/assets/logo-nome.png"/><span className="eyebrow">BEM-VINDO DE VOLTA</span><h2>Acesse sua conta</h2><p>Entre para acompanhar suas equipes.</p><form onSubmit={submit}><label>CPF<input name="cpf" placeholder="Digite seu CPF" required/></label><label>Senha<span className="password-field"><input name="senha" type={showPassword?"text":"password"} defaultValue="toth123" required/><button type="button" onClick={()=>setShowPassword(!showPassword)} aria-label={showPassword?"Ocultar senha":"Mostrar senha"} title={showPassword?"Ocultar senha":"Mostrar senha"}>{showPassword?<EyeOff/>:<Eye/>}</button></span></label>{error&&<small className="form-error">{error}</small>}<Button type="submit">{loading?"Entrando...":"Entrar na plataforma"}</Button></form></div></div>}</main>
}

function Shell({onLogout}:{onLogout:()=>void}){
  const location=useLocation();const [menu,setMenu]=useState(false),[siteOpen,setSiteOpen]=useState(false),[site,setSite]=useState("Obra ativa"),[siteList,setSiteList]=useState<ApiSite[]>(fallbackApiSites),[dark,setDark]=useState(localStorage.getItem("toth-theme")!=="light");
  const gestor=JSON.parse(localStorage.getItem("toth-gestor")||'{"nome":"Gestor TOTH"}') as {nome:string};
  useEffect(()=>{api<ApiSite[]>("/obras?ativos=true").then(x=>{if(x){setSiteList(x);const selected=x.find(s=>String(s.id)===localStorage.getItem("toth-obra"));setSite(selected?.nome||x[0]?.nome||"Obra ativa")}})},[]);
  useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("toth-theme",dark?"dark":"light")},[dark]);
  const links=[["/dashboard",<LayoutDashboard/>,"Dashboard"],["/funcionarios",<Users/>,"Funcionários"],["/jornadas",<CalendarDays/>,"Lista de presença"],["/conferencia",<FileText/>,"Conferência"],["/obras",<Building2/>,"Obras"],["/cargos",<BriefcaseBusiness/>,"Cargos"]] as const;
  const logout=()=>{localStorage.removeItem("toth-token");localStorage.removeItem("toth-gestor");localStorage.removeItem("toth-api-session-id");localStorage.removeItem("toth-api-session-worksite-id");localStorage.removeItem("toth-manager-cpf");onLogout()};
  return <div className="app-shell"><aside className={menu?"open":""}><div className="brand"><img src="/assets/logo-nome.png"/></div><button className="mobile-close" onClick={()=>setMenu(false)}><X/></button><small>MENU PRINCIPAL</small><nav>{links.map(l=><NavLink key={l[0]} to={l[0]} onClick={()=>setMenu(false)}>{l[1]}<span>{l[2]}</span></NavLink>)}</nav><div className="aside-bottom"><button className="settings-theme" onClick={()=>setDark(!dark)} title={dark?"Usar tema claro":"Usar tema escuro"}><Settings/><span>Configurações<small>{dark?"Usar tema claro":"Usar tema escuro"}</small></span>{dark?<Sun/>:<Moon/>}</button><button onClick={logout}><LogOut/>Sair da conta</button></div></aside><div className="main-area"><header><button className="menu-btn" onClick={()=>setMenu(true)}><Menu/></button><div><span className="header-kicker">{location.pathname.startsWith("/jornadas/")?"DETALHE DA LISTA DE PRESENÇA":(pageTitles[location.pathname]||"PAINEL ADMINISTRATIVO").toUpperCase()}</span><h1>Registro de Ponto</h1></div><div className="header-actions"><div className="site-switch"><button onClick={()=>setSiteOpen(!siteOpen)}><Building2/><span><small>OBRA ATUAL</small>{site}</span><ChevronDown/></button>{siteOpen&&<div>{siteList.map(s=><button key={s.id} onClick={()=>{setSite(s.nome);localStorage.setItem("toth-obra",String(s.id));window.dispatchEvent(new Event("toth-worksite-change"));setSiteOpen(false)}}>{s.nome}</button>)}</div>}</div><button className="icon-btn"><Bell/><i/></button><button className="profile"><span>GT</span><div><b>{gestor.nome}</b><small>Administrador</small></div></button></div></header><main className="content"><Routes><Route path="/dashboard" element={<Dashboard/>}/><Route path="/funcionarios" element={<Employees/>}/><Route path="/jornadas" element={<Journeys/>}/><Route path="/jornadas/:id" element={<JourneyDetail/>}/><Route path="/conferencia" element={<AttendanceReview/>}/><Route path="/obras" element={<Sites/>}/><Route path="/cargos" element={<Roles/>}/><Route path="*" element={<Navigate to="/dashboard"/>}/></Routes></main></div></div>
}

function Metric({icon,label,value,detail,tone}:{icon:ReactNode;label:string;value:string;detail:string;tone:string}){return <article className="metric"><div className={`metric-icon ${tone}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div><div className="metric-spark"><i/><i/><i/><i/><i/></div></article>}
function Dashboard(){
  const obraId=useActiveWorksite();const [data,setData]=useState<DashboardData>(demoDashboard);useEffect(()=>{if(obraId)api<DashboardData>(`/dashboard?obra_id=${obraId}`).then(x=>x&&setData(x))},[obraId]);
  const chart=(data.presencaDiaria||[]).map(x=>({day:formatDate(x.data).slice(0,5),presentes:x.presentes}));const absent=Math.max(0,data.resumo.funcionariosAtivos-data.resumo.presentes-data.resumo.pendentes);const pie=[{name:"Presentes",value:data.resumo.presentes,color:"#35d39a"},{name:"Pendentes",value:data.resumo.pendentes,color:"#ffbe55"},{name:"Ausentes",value:absent,color:"#ff5d7a"}];
  return <><PageIntro title="Visão geral da operação" text={`Resumo consolidado de ${formatDate(data.data)}.`}/><section className="metrics metrics-three"><Metric icon={<Users/>} label="Funcionários ativos" value={String(data.resumo.funcionariosAtivos)} detail="Vinculados à obra" tone="purple"/><Metric icon={<UserCheck/>} label="Presentes agora" value={String(data.resumo.presentes)} detail="Já registraram o primeiro ponto" tone="green"/><Metric icon={<Clock3/>} label="Pendências hoje" value={String(data.resumo.pendentes)} detail="Ainda sem primeiro ponto" tone="yellow"/></section><section className="grid-charts"><article className="panel chart-large"><div className="panel-head"><div><h3>Presença por obra</h3><p>Funcionários presentes por dia conforme a lista de presença</p></div></div><ResponsiveContainer width="100%" height={280}><BarChart data={chart}><CartesianGrid stroke="#eceaf5" vertical={false}/><XAxis dataKey="day"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="presentes" fill="#ff9548" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></article><article className="panel"><div className="panel-head"><div><h3>Status de hoje</h3><p>Primeiro ponto define presença</p></div></div><div className="donut-wrap"><ResponsiveContainer width="100%" height={205}><PieChart><Pie data={pie} dataKey="value" innerRadius={65} outerRadius={88}>{pie.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{data.resumo.funcionariosAtivos}</strong><span>Total</span></div></div><div className="legend">{pie.map(x=><span key={x.name}><i style={{background:x.color}}/>{x.name}<b>{x.value}</b></span>)}</div></article></section><RecentJourneys/></>
}

function Employees(){
  const obraId=useActiveWorksite();const [raw,setRaw]=useState<ApiEmployee[]>(fallbackApiEmployees),[roles,setRoles]=useState<ApiRole[]>(fallbackApiRoles),[search,setSearch]=useState(""),[editing,setEditing]=useState<ApiEmployee|null>(null),[open,setOpen]=useState(false),[filtersOpen,setFiltersOpen]=useState(false),[roleFilter,setRoleFilter]=useState(""),[message,setMessage]=useState(""),[busyId,setBusyId]=useState<string|null>(null);
  const load=()=>obraId&&api<ApiEmployee[]>(`/funcionarios?obra_id=${obraId}`).then(x=>x&&setRaw(x));useEffect(()=>{load();api<ApiRole[]>("/cargos?ativos=true").then(x=>x&&setRoles(x))},[obraId]);
  const list=raw.map(employeeFromApi),filtered=list.filter(x=>`${x.name} ${x.cpf} ${x.role}`.toLowerCase().includes(search.toLowerCase())&&(!roleFilter||x.role===roleFilter));
  const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setMessage("");const f=new FormData(e.currentTarget);const payload={nome:f.get("nome"),cpf:f.get("cpf"),matricula:f.get("matricula"),telefone:f.get("telefone"),email:f.get("email"),cargo_id:Number(f.get("cargo_id"))||null,obra_id:editing?undefined:Number(obraId),ativo:editing?Boolean(editing.ativo):true};const employeeId=editing?.id_api||editing?.id;const result=await api<ApiEmployee>(`/funcionarios${employeeId?`/${employeeId}`:""}`,{method:editing?"PUT":"POST",body:JSON.stringify(payload)});if(result){setOpen(false);setEditing(null);load()}else setMessage("Não foi possível salvar o funcionário. Verifique a conexão com a API.")};
  const toggleActive=async(employee:ApiEmployee)=>{const employeeId=String(employee.id_api||employee.id);setBusyId(employeeId);setMessage("");const result=await api<ApiEmployee>(`/funcionarios/${employeeId}/ativo`,{method:"PATCH",body:JSON.stringify({ativo:!Boolean(employee.ativo)})});setBusyId(null);if(result){setMessage(employee.ativo?"Funcionário inativado com sucesso.":"Funcionário reativado com sucesso.");load()}else setMessage("Não foi possível alterar o status do funcionário. Verifique a conexão com a API.")};
  return <><PageIntro title="Gestão de funcionários" text="Funcionários vinculados ? obra selecionada." action={<Button onClick={()=>{setEditing(null);setOpen(true)}}><Plus/>Novo funcionário</Button>}/>{message&&<div className="success-message">{message}</div>}<section className="panel table-panel"><Toolbar search={search} setSearch={setSearch} onFilter={()=>setFiltersOpen(!filtersOpen)} active={filtersOpen||Boolean(roleFilter)}/>{filtersOpen&&<div className="filter-panel"><label>Cargo<select value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}><option value="">Todos os cargos</option>{roles.map(r=><option key={r.id} value={r.nome}>{r.nome}</option>)}</select></label><button onClick={()=>{setRoleFilter("");setSearch("")}}>Limpar filtros</button></div>}<div className="table-scroll"><table><thead><tr><th>Funcionário</th><th>Matrícula</th><th>CPF</th><th>Cargo</th><th>Obra</th><th>Status</th><th/></tr></thead><tbody>{filtered.map(x=>{const source=raw.find(r=>r.id===x.id)!;const sourceId=String(source.id_api||source.id);return <tr key={sourceId} className={source.ativo?"":"inactive-row"}><td><div className="person"><span>{x.name.split(" ").map(v=>v[0]).slice(0,2)}</span><div><b>{x.name}</b><small>{x.phone}</small></div></div></td><td>{x.matricula}</td><td>{x.cpf}</td><td>{x.role}</td><td>{x.site}</td><td><Status value={x.status}/></td><td><div className="row-actions"><button type="button" onClick={()=>{setEditing(source);setOpen(true)}}><Edit3/></button><button type="button" disabled={busyId===sourceId} className={source.ativo?"":"reactivate"} title={source.ativo?"Inativar funcionário":"Reativar funcionário"} onClick={()=>toggleActive(source)}><Trash2/></button></div></td></tr>})}</tbody></table></div><div className="table-foot">Exibindo {filtered.length} funcionários</div></section>{open&&<EmployeeModal employee={editing} roles={roles} save={save} close={()=>setOpen(false)}/>}</>
}
function EmployeeModal({employee,roles,save,close}:{employee:ApiEmployee|null;roles:ApiRole[];save:(e:FormEvent<HTMLFormElement>)=>void;close:()=>void}){const registration=employee?.matricula||"Gerada automaticamente";return <div className="modal-backdrop"><div className="form-modal"><div className="modal-head"><div><span className="eyebrow">CADASTRO</span><h2>{employee?"Editar funcionário":"Novo funcionário"}</h2></div><button onClick={close}><X/></button></div><form onSubmit={save}><label>Nome<input name="nome" required defaultValue={employee?.nome}/></label><div className="form-grid"><label>CPF<input name="cpf" required defaultValue={employee?.cpf}/></label><label>Telefone<input name="telefone" defaultValue={employee?.telefone||""}/></label><label>Cargo<select name="cargo_id" required defaultValue={employee?.cargo_id||""}><option value="" disabled>Selecione um cargo</option>{roles.map(r=><option key={r.id} value={r.id}>{r.nome}</option>)}</select></label><label>Matrícula<input name="matricula" required readOnly value={registration}/></label><label>E-mail<input name="email" type="email" defaultValue={employee?.email||""}/></label></div><div className="modal-actions"><Button variant="ghost" onClick={close}>Cancelar</Button><Button type="submit">Salvar funcionário</Button></div></form></div></div>}

function RecentJourneys(){const obraId=useActiveWorksite();const [list,setList]=useState<ApiJourney[]>([]),nav=useNavigate();useEffect(()=>{if(obraId)api<ApiJourney[]>(`/jornadas?obra_id=${obraId}`).then(x=>x&&setList(x))},[obraId]);return <section className="panel table-panel"><div className="panel-head padded"><div><h3>Listas de presença recentes</h3><p>Registros carregados da API</p></div><Button variant="ghost" onClick={()=>nav("/jornadas")}>Ver detalhes</Button></div><div className="table-scroll"><table><thead><tr><th>Data</th><th>Funcionários</th><th>Presentes</th><th>Status</th></tr></thead><tbody>{list.map(j=><tr key={j.id} className="click-row" onClick={()=>nav(`/jornadas/${j.id}`)}><td><strong className="date-primary">{formatDate(j.data)}</strong></td><td>{j.total_funcionarios}</td><td>{j.presentes}</td><td><Status value={j.status}/></td></tr>)}</tbody></table></div></section>}
function Journeys(){
  const obraId=useActiveWorksite();const [list,setList]=useState<ApiJourney[]>([]),[search,setSearch]=useState(""),[filtersOpen,setFiltersOpen]=useState(false),[statusFilter,setStatusFilter]=useState(""),[dateFilter,setDateFilter]=useState(""),[openGroup,setOpenGroup]=useState<string|null>(null),nav=useNavigate();
  useEffect(()=>{if(obraId)api<ApiJourney[]>(`/jornadas?obra_id=${obraId}`).then(x=>x&&setList(x))},[obraId]);
  const filtered=list.filter(j=>matchesSearch(`${j.id} ${j.obra_nome} ${j.obra_codigo} ${formatDate(j.data)} ${j.status}`,search)&&(!statusFilter||j.status===statusFilter)&&(!dateFilter||j.data===dateFilter));
  const groups=Array.from(filtered.reduce((map,j)=>{const key=`${j.data}-${j.obra_nome}`;const current=map.get(key)||{key,data:j.data,obra:j.obra_nome,presentes:0,total:0,records:[] as ApiJourney[]};current.presentes=Math.max(current.presentes,j.presentes);current.total=Math.max(current.total,j.total_funcionarios);current.records.push(j);map.set(key,current);return map},new Map<string,{key:string;data:string;obra:string;presentes:number;total:number;records:ApiJourney[]}>()).values());
  const currentWorksite=list[0];
  const worksiteLabel=currentWorksite?`${currentWorksite.obra_nome} ? ${currentWorksite.obra_codigo}`:"Obra selecionada";
  return <><PageIntro title={<span className="title-with-meta">Lista de presença <small>{worksiteLabel}</small></span>} text="Consulte as listas de presença agrupadas por data e obra."/><section className="panel table-panel"><Toolbar search={search} setSearch={setSearch} onFilter={()=>setFiltersOpen(!filtersOpen)} active={filtersOpen||Boolean(statusFilter)||Boolean(dateFilter)}/>{filtersOpen&&<div className="filter-panel"><label>Data<input type="date" value={dateFilter} onChange={e=>setDateFilter(e.target.value)}/></label><label>Status<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Todos os status</option><option value="ABERTA">Aberto</option><option value="ENCERRADA">Finalizado</option><option value="CANCELADA">Cancelado</option></select></label><button onClick={()=>{setDateFilter("");setStatusFilter("");setSearch("")}}>Limpar filtros</button></div>}<div className="table-scroll"><table><thead><tr><th>Data</th><th>Obra</th><th>Funcionários presentes</th><th>Equipe</th><th>Listas</th><th/></tr></thead><tbody>{groups.map(g=><><tr key={g.key} className="click-row group-row" onClick={()=>setOpenGroup(openGroup===g.key?null:g.key)}><td><strong className="date-primary">{formatDate(g.data)}</strong></td><td>{g.obra}</td><td>{g.presentes}</td><td>{g.total}</td><td>{g.records.length}</td><td>{openGroup===g.key?<ChevronUp/>:<ChevronDown/>}</td></tr>{openGroup===g.key&&g.records.map(j=><tr key={j.id} className="group-detail-row" onClick={()=>nav(`/jornadas/${j.id}`)}><td><strong>#{j.id}</strong></td><td><Status value={j.status}/></td><td colSpan={2}>{j.obra_codigo}</td><td>{j.presentes}/{j.total_funcionarios}</td><td><Eye/></td></tr>)}</>)}</tbody></table></div><div className="table-foot">Exibindo {groups.length} grupos de presença</div></section></>}
function AttendanceReview(){
  const obraId=useActiveWorksite();const [list,setList]=useState<ApiAttendance[]>([]),[search,setSearch]=useState(""),[filtersOpen,setFiltersOpen]=useState(false),[statusFilter,setStatusFilter]=useState(""),[openGroup,setOpenGroup]=useState<string|null>(null);
  useEffect(()=>{if(obraId)api<ApiAttendance[]>(`/conferencia?obra_id=${obraId}`).then(x=>x&&setList(x))},[obraId]);
  const statusLabel=(item:ApiAttendance)=>item.foremanStatus==="nao_marcado"?"Pendente":item.pointPresence===(item.foremanStatus==="presente")?"Regular":"Atenção";
  const foremanLabel=(item:ApiAttendance)=>item.foremanStatus==="presente"?"Presente":item.foremanStatus==="ausente"?"Ausente":"Pendente";
  const filtered=list.filter(x=>matchesSearch(`${x.employeeName} ${x.roleName} ${x.worksiteName} ${formatDate(x.date)}`,search)&&(!statusFilter||statusLabel(x)===statusFilter));
  const groups=Array.from(filtered.reduce((map,item)=>{const key=`${item.date}-${item.worksiteName}`;const current=map.get(key)||{key,date:item.date,worksiteName:item.worksiteName,presentes:0,total:0,items:[] as ApiAttendance[]};current.total+=1;if(item.foremanStatus==="presente")current.presentes+=1;current.items.push(item);map.set(key,current);return map},new Map<string,{key:string;date:string;worksiteName:string;presentes:number;total:number;items:ApiAttendance[]}>()).values());
  return <><PageIntro title="Conferência de presença" text="Compare os pontos batidos pelos funcionários com a lista realizada pelo encarregado."/><section className="panel table-panel"><Toolbar search={search} setSearch={setSearch} onFilter={()=>setFiltersOpen(!filtersOpen)} active={filtersOpen||Boolean(statusFilter)}/>{filtersOpen&&<div className="filter-panel"><label>Status<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Todos</option><option value="Regular">Regular</option><option value="Atenção">Atenção</option><option value="Pendente">Pendente</option></select></label><button onClick={()=>{setStatusFilter("");setSearch("")}}>Limpar filtros</button></div>}<div className="table-scroll"><table><thead><tr><th>Data</th><th>Obra</th><th>Funcionários presentes</th><th>Total conferido</th><th>Status</th><th/></tr></thead><tbody>{groups.map(g=><><tr key={g.key} className="click-row group-row" onClick={()=>setOpenGroup(openGroup===g.key?null:g.key)}><td><strong className="date-primary">{formatDate(g.date)}</strong></td><td>{g.worksiteName}</td><td>{g.presentes}</td><td>{g.total}</td><td><Status value={g.presentes===g.total?"Regular":"Atenção"}/></td><td>{openGroup===g.key?<ChevronUp/>:<ChevronDown/>}</td></tr>{openGroup===g.key&&<tr className="group-detail-row"><td colSpan={6}><div className="group-details"><table><thead><tr><th>Funcionário</th><th>Cargo</th><th>Pontos</th><th>Lista do encarregado</th><th>Status</th><th>Observação</th></tr></thead><tbody>{g.items.map(item=><tr key={item.id}><td><div className="person"><span>{item.employeeName.split(" ").map(v=>v[0]).slice(0,2)}</span><div><b>{item.employeeName}</b><small>{item.worksiteName}</small></div></div></td><td>{item.roleName}</td><td><strong>{item.timeEntryCount}/4</strong><small className="cell-small">{item.firstTime||"--:--"} - {item.lastTime||"--:--"}</small></td><td><Status value={foremanLabel(item)}/></td><td><Status value={statusLabel(item)}/></td><td>{item.foremanObservation||"-"}</td></tr>)}</tbody></table></div></td></tr>}</>)}</tbody></table></div><div className="table-foot">Exibindo {groups.length} grupos de conferência</div></section></>
}
function JourneyDetail(){
  const {id}=useParams(),nav=useNavigate(),[j,setJ]=useState<ApiJourneyDetail|null>(null),[expanded,setExpanded]=useState<number|null>(null),[punches,setPunches]=useState<Record<number,ApiPunch[]>>({}),[decision,setDecision]=useState<Record<number,string>>({}),[editTime,setEditTime]=useState<Record<number,string>>({}),[reason,setReason]=useState<Record<number,string>>({}),[message,setMessage]=useState("");
  const load=()=>api<ApiJourneyDetail>(`/jornadas/${id}`).then(setJ);useEffect(()=>{void load()},[id]);
  const toggle=async(f:{funcionario_id:number})=>{if(expanded===f.funcionario_id){setExpanded(null);return}setExpanded(f.funcionario_id);if(!punches[f.funcionario_id]){const rows=await api<ApiPunch[]>(`/jornadas/${id}/funcionarios/${f.funcionario_id}/batidas`);if(rows)setPunches(v=>({...v,[f.funcionario_id]:rows}))}};
  const saveSituation=async(funcionarioId:number)=>{const status=decision[funcionarioId];if(!status)return;const result=await api(`/jornadas/${id}/funcionarios/${funcionarioId}/status`,{method:"PATCH",body:JSON.stringify({status})});if(result){setMessage("Situação do funcionário atualizada com sucesso.");load()}};
  const saveCorrection=async(funcionarioId:number)=>{const value=editTime[funcionarioId];if(!value||!j)return;const current=punches[funcionarioId]||[];const data_hora=`${j.data}T${value}:00`;const tipo=current.length%2===0?"ENTRADA":"SAIDA";const result=await api<ApiPunch>("/batidas",{method:"POST",body:JSON.stringify({jornada_id:Number(id),funcionario_id:funcionarioId,tipo,data_hora,origem:"MANUAL",observacao:reason[funcionarioId]||null})});if(result){const rows=await api<ApiPunch[]>(`/jornadas/${id}/funcionarios/${funcionarioId}/batidas`);if(rows)setPunches(v=>({...v,[funcionarioId]:rows}));setMessage("Batida corrigida com sucesso.");load()}};
  const finish=async()=>{if(await api(`/jornadas/${id}/status`,{method:"PATCH",body:JSON.stringify({status:"ENCERRADA"})})){setMessage("Lista de presença finalizada com sucesso.");load()}};
  if(!j)return <section className="panel journey-card"><h3>Carregando lista de presença...</h3></section>;
  return <><button className="back" onClick={()=>nav("/jornadas")}><ArrowLeft/>Voltar para lista de presença</button><PageIntro title={j.obra_nome} text={`${j.obra_codigo} ? ${formatDate(j.data)}`} action={<div className="journey-actions"><Status value={j.status}/>{j.status==="ABERTA"&&<Button onClick={finish}><CheckCircle2/>Finalizar lista</Button>}</div>}/>{message&&<div className="success-message">{message}</div>}<section className="panel presence-list"><div className="presence-head"><span>Funcionário</span><span>Status</span><span>Cargo</span><span>Batidas</span><span/></div>{j.funcionarios.map(f=>{const open=expanded===f.funcionario_id;const rows=punches[f.funcionario_id]||[];const absent=f.status==="AUSENTE"||f.status==="ABONADO";const regular=f.status==="REGULAR";return <div className="presence-item" key={f.funcionario_id}><button className="presence-row" onClick={()=>toggle(f)}><span className={`presence-dot ${regular||f.status==="ABONADO"?"green":absent?"red":"yellow"}`}/><b>{f.nome}</b><Status value={f.status}/><span>{f.cargo_nome||"Sem cargo"}</span><span>{f.total_batidas}</span>{open?<ChevronUp/>:<ChevronDown/>}</button>{open&&<div className="presence-details">{absent?<div className="absence-actions"><p>Defina a situação do funcionário nesta data.</p><div><button className={decision[f.funcionario_id]==="ABONADO"?"selected abonar":"abonar"} onClick={()=>setDecision(v=>({...v,[f.funcionario_id]:"ABONADO"}))}>ABONAR</button><button className={decision[f.funcionario_id]==="AUSENTE"?"selected ausentar":"ausentar"} onClick={()=>setDecision(v=>({...v,[f.funcionario_id]:"AUSENTE"}))}>AUSENTAR</button><button className="save-action" disabled={!decision[f.funcionario_id]} onClick={()=>saveSituation(f.funcionario_id)}>SALVAR</button></div></div>:regular?<PunchBlocks punches={rows}/>:<div className="correction-area"><PunchBlocks punches={rows} showError/><div className="correction-form"><label>Horário correto<input type="time" value={editTime[f.funcionario_id]||""} onChange={e=>setEditTime(v=>({...v,[f.funcionario_id]:e.target.value}))}/></label><label>Razão do erro (opcional)<input placeholder="Ex.: falha no equipamento" value={reason[f.funcionario_id]||""} onChange={e=>setReason(v=>({...v,[f.funcionario_id]:e.target.value}))}/></label><button className="save-action" disabled={!editTime[f.funcionario_id]} onClick={()=>saveCorrection(f.funcionario_id)}>SALVAR</button></div></div>}</div>}</div>})}</section></>
}
function PunchBlocks({punches,showError=false}:{punches:ApiPunch[];showError?:boolean}){const values=punches.slice(0,4);return <div className="punch-blocks">{values.map(p=><span key={p.id}>{formatTime(p.data_hora)}</span>)}{showError&&values.length<4&&<span className="error-block">ERRO</span>}</div>}

function EntityModal({title,fields,initial,save,close}:{title:string;fields:Array<{name:string;label:string;required?:boolean}>;initial:Record<string,unknown>|null;save:(e:FormEvent<HTMLFormElement>)=>void;close:()=>void}){return <div className="modal-backdrop"><div className="form-modal"><div className="modal-head"><h2>{title}</h2><button onClick={close}><X/></button></div><form onSubmit={save}><div className="form-grid">{fields.map(f=><label key={f.name}>{f.label}<input name={f.name} required={f.required} defaultValue={String(initial?.[f.name]||"")}/></label>)}</div><div className="modal-actions"><Button variant="ghost" onClick={close}>Cancelar</Button><Button type="submit">Salvar</Button></div></form></div></div>}
function SiteModal({site,foremen,save,close}:{site:ApiSite|null;foremen:ApiEmployee[];save:(e:FormEvent<HTMLFormElement>)=>void;close:()=>void}){const current=site?.responsavel||"";const hasCurrent=current&&foremen.every(f=>f.nome!==current);return <div className="modal-backdrop"><div className="form-modal"><div className="modal-head"><h2>{site?"Editar obra":"Nova obra"}</h2><button onClick={close}><X/></button></div><form onSubmit={save}><div className="form-grid"><label>Nome<input name="nome" required defaultValue={site?.nome||""}/></label><label>Código<input name="codigo" required defaultValue={site?.codigo||""}/></label><label>Endereço<input name="endereco" defaultValue={site?.endereco||""}/></label><label>Cidade<input name="cidade" defaultValue={site?.cidade||""}/></label><label>Encarregado<select name="responsavel" defaultValue={current}><option value="">Selecione um encarregado</option>{hasCurrent&&<option value={current}>{current}</option>}{foremen.map(f=><option key={f.id_api||f.id} value={f.nome}>{f.nome}</option>)}</select></label><label>Data de início<input name="data_inicio" type="date" defaultValue={site?.data_inicio||""}/></label></div><div className="modal-actions"><Button variant="ghost" onClick={close}>Cancelar</Button><Button type="submit">Salvar</Button></div></form></div></div>}
function Sites(){const [list,setList]=useState<ApiSite[]>(fallbackApiSites),[editing,setEditing]=useState<ApiSite|null>(null),[open,setOpen]=useState(false),[foremen,setForemen]=useState<ApiEmployee[]>([]);const load=()=>api<ApiSite[]>("/obras").then(x=>x&&setList(x));const loadForemen=()=>api<ApiEmployee[]>("/funcionarios").then(x=>x&&setForemen(x.filter(e=>normalizeText(e.cargo_nome||"")==="encarregado"&&Boolean(e.ativo))));useEffect(()=>{void load();void loadForemen()},[]);const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const result=await api<ApiSite>(`/obras${editing?`/${editing.id}`:""}`,{method:editing?"PUT":"POST",body:JSON.stringify({...f,ativa:true})});if(result){setOpen(false);load()}};const remove=async(id:number)=>{if(await api(`/obras/${id}`,{method:"DELETE"}))load()};return <><PageIntro title="Obras" text="Gerencie locais e encarregados de cada projeto." action={<Button onClick={()=>{setEditing(null);setOpen(true)}}><Plus/>Nova obra</Button>}/><section className="cards-grid">{list.map((s,i)=><article className="site-card" key={s.id}><div className={`site-cover cover-${i%3}`}><Building2/><Status value={s.ativa?"Em andamento":"Inativa"}/></div><div className="site-body"><h3>{s.nome}</h3><p>{s.codigo} ? {s.endereco||"Sem endereço"} {s.cidade||""}</p><div className="site-stats"><span><HardHat/><b>{s.responsavel||"Encarregado não informado"}</b></span></div><div className="row-actions"><button onClick={()=>{setEditing(s);setOpen(true)}}><Edit3/></button><button onClick={()=>remove(s.id)}><Trash2/></button></div></div></article>)}</section>{open&&<SiteModal site={editing} foremen={foremen} save={save} close={()=>setOpen(false)}/>}</>}
function Roles(){const [list,setList]=useState<ApiRole[]>(fallbackApiRoles),[editing,setEditing]=useState<ApiRole|null>(null),[open,setOpen]=useState(false),[message,setMessage]=useState("");const load=()=>api<ApiRole[]>("/cargos").then(x=>x&&setList(x));useEffect(()=>{void load()},[]);const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setMessage("");const f=Object.fromEntries(new FormData(e.currentTarget));const result=await api<ApiRole>(`/cargos${editing?`/${editing.id}`:""}`,{method:editing?"PUT":"POST",body:JSON.stringify({...f,ativo:editing?Boolean(editing.ativo):true})});if(result){setOpen(false);setEditing(null);load()}else setMessage("Não foi possível salvar o cargo.")};const toggleActive=async(role:ApiRole)=>{setMessage("");const result=await api<ApiRole>(`/cargos/${role.id}/ativo`,{method:"PATCH",body:JSON.stringify({ativo:!Boolean(role.ativo)})});if(result){setMessage(role.ativo?"Cargo inativado com sucesso.":"Cargo reativado com sucesso.");load()}else setMessage("Não foi possível alterar o status do cargo.")};const remove=async(role:ApiRole)=>{if(!window.confirm(`Excluir o cargo "${role.nome}" definitivamente?`))return;setMessage("");if(await api(`/cargos/${role.id}`,{method:"DELETE"})){setMessage("Cargo excluído com sucesso.");load()}else setMessage("Não foi possível excluir o cargo. Verifique se há funcionários vinculados.")};return <><PageIntro title="Cargos" text="Configure as funções da empresa." action={<Button onClick={()=>{setEditing(null);setOpen(true)}}><Plus/>Novo cargo</Button>}/>{message&&<div className="success-message">{message}</div>}<section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Cargo</th><th>Descrição</th><th>Status</th><th/></tr></thead><tbody>{list.map(r=><tr key={r.id} className={r.ativo?"":"inactive-row"}><td><div className="role-name"><span><BriefcaseBusiness/></span><b>{r.nome}</b></div></td><td>{r.descricao||"Sem descrição"}</td><td><Status value={r.ativo?"Ativo":"Inativo"}/></td><td><div className="row-actions"><button type="button" onClick={()=>{setEditing(r);setOpen(true)}} title="Editar cargo"><Edit3/></button><button type="button" className={r.ativo?"":"reactivate"} onClick={()=>toggleActive(r)} title={r.ativo?"Inativar cargo":"Reativar cargo"}><XCircle/></button><button type="button" onClick={()=>remove(r)} title="Excluir cargo"><Trash2/></button></div></td></tr>)}</tbody></table></div></section>{open&&<EntityModal title={editing?"Editar cargo":"Novo cargo"} fields={[{name:"nome",label:"Nome",required:true},{name:"descricao",label:"Descrição"}]} initial={editing} save={save} close={()=>setOpen(false)}/>}</>}

export default function App(){const [auth,setAuth]=useState(Boolean(localStorage.getItem("toth-token")));return auth?<Shell onLogout={()=>setAuth(false)}/>:<Landing onLogin={()=>setAuth(true)}/>}


